### ISSUE TITLE
Scroll position

### ISSUE THREAD

**Issue by Barruchou** [oleggrishechkin/react-viewport-list#27]
Hi, thanks for your component.

It would be really cool if we could directly define the position of the scroll rather than going through the indexes of "viewport". This would return the user to the exact location of their scroll.

Or to have the Y position of each child.

I remain available if it is not clear to you,
Thanks.

**Comment by oleggrishechkin** [comment]
Hi @Barruchou!

Scroll to position can work incorrectly. scrollHeight and scrollTop changed automatically during the scroll because new rendered items can have different height.

But you can try to use initialOffset=<you_scroll_top> with initialIndex=0 for initial scrolling and offset/index params in scrollToIndex method).

Offset just adds specified value to the current scrollTop.

**Comment by Barruchou** [comment]
Thanks for your answer, I'm not sure I fully understand the doc regarding "initialOffset"

**Comment by oleggrishechkin** [comment]
I think I should clarify this case in docs and rewrite `initialOffset ` decription
