### ISSUE TITLE
Usage with display: grid 

### ISSUE THREAD

**Issue by nevolgograd** [oleggrishechkin/react-viewport-list#3]
First of all thanks for this package, really nice to have an alternative for react-virtualized.

 I'm trying to create a simple two column grid with this css applied to `scroll-container`, but it completely brakes everything:
```
{
    display: grid;
    grid-template-columns: 50% 50%;
    gap: 16px 8px;
}
```

I've try to add it to your [example](https://oleggrishechkin.github.io/react-viewport-list/) and got the same result.

Can you please provide correct way of css grid usage? Thx.

**Comment by oleggrishechkin** [comment]
Multicolumn grid is unsupported, you can try to use ViewPortList this way:

‘’’javascript
<div className=“row”>
    <div className=“first-column”>
        ... render ViewPortList 1
    </div>
    <div className=“second-column”>
        ... render ViewPortList 2
    </div>
</div>
‘’’

**Comment by nevolgograd** [comment]
It worked, but...

![Screen-Recording-2020-05-11-at-1](https://user-images.githubusercontent.com/17023612/81558143-da4b4e80-9395-11ea-91e5-7d2ce570f946.gif)

**Comment by oleggrishechkin** [comment]
Please, show me your JSX code



so, you can try this markup - 

```javascript
<div className=“column”>
    <ViewPortList ...>
        {(...) =>
            <div className=“row”>
                ...
            </div>
        }
    </ViewPortList>
</div>
```

**Comment by spacepolice10** [comment]
Type of jiggering showed by [nevolgograd](https://github.com/nevolgograd) is usually happens if two lists near each other has common scroll parent but different height. I tried to implement parallel lists, synchronized by one parent but slightly different in height & I noticed the same behavior. The shorter one is always changing its position a bit. So I believe it is not possible to make different in height lists sync correctly
