### ISSUE TITLE
Why does it work when height varies?

### ISSUE THREAD

**Issue by lcswillems** [oleggrishechkin/react-viewport-list#50]
Hi,

I have just had a look to the CodeSandBox given in the README: https://codesandbox.io/s/react-viewport-list-xw2rt

The height of each message varies. However, it seems that the correct messages are rendered whatever the scroll position. How is it possible?

**Comment by oleggrishechkin** [comment]
Hi, @lcswillems . Component don't know height of each message before message's render and estimates message's height via itemMinHeight or automatically (by first rendered message). When you scrolling some of the messages hide under scroll (virtually, they will replaced by blank space) and component compensate the scroll position to prevent layout shift. So, react-viewport-list don't know the real message position and it can vary by different scroll usage.

For example:

1-10 messages rendered. Estimated message size is 50px.
You scroll by 100px. Component know that 2 next messages can be rendered. (100 / 50 = 2). Also component exactly know what items should be hide at top (since top messages already rendered and we know their real size). Let's mark 1-2 messages as 50px for example.
Component will render 3-12 messages at next tick and then it will check what messages rendered and how many messages should be rendered or what messages should be hidden.

Component estimates what messages can fill viewport, rendered them and then correct it - render more or less messages.

**Comment by lcswillems** [comment]
Thanks a lot @oleggrishechkin for the explanation!!
